sudo: required
language: generic 

services:
    - docker
before_install:
  - docker build -t hegdesandesh25/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hegdesandesh25/react-test npm test -- --coverage

after_success:
   - docker build -t hegdesandesh25/multi-client ./client
   - docker build -t hegdesandesh25/multi-nginx  ./nginx
   - docker build -t hegdesandesh25/multi-server ./server
   - docker build -t hegdesandesh25/multi-worker ./worker
  

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


- docker push hegdesandesh25/multi-client
- docker push hegdesandesh25/multi-nginx
- docker push hegdesandesh25/multi-server
- docker push hegdesandesh25/multi-worker

